application:
  port: 5000
  protocol: https
  host: 0.0.0.0
  base_usr: ""

#Необходимо довать настройки соединения с DB и Redis

debug: false

secret:
  secret_key: ""
  token_expiration: 0
  hmac_secret: ""

frontend_url: ""